### ISSUE TITLE
Solstice Mines dialogue plays twice

### ISSUE THREAD

**Issue by markdegica** [GooborgStudios/synglechance#42] opened 2018-05-01 16:11 UTC
When stepping on the edge of the gap in the Mines, the dialogue will seemingly play twice. The first dialogue will play with Silver asking you to step away from the edge, and then it will replay again with the journal beginning to glow.

**Comment by markdegica** [comment] 2018-05-01 16:13
<img width="1280" alt="screen shot 2018-04-30 at 3 29 14 pm" src="https://user-images.githubusercontent.com/38886447/39481346-192ec924-4d39-11e8-91dc-f126be51aa71.png">

**Comment by vinyldarkscratch** [comment] 2018-05-02 09:02
Confirmed.  Possible that it's related to #36?  I'll have to look into it more...

**Comment by vinyldarkscratch** [comment] 2018-05-02 09:03
Actually wait, the dialogue's slightly different -- it seems like there's more the second time around.  I'll have to figure out what's going on with it...

**Comment by vinyldarkscratch** [comment] 2018-05-02 09:46
This seems to be fixed now after I fixed #43, most likely another issue with using the wrong files.  Hehe, oops!

**Closed by vinyldarkscratch** 2018-05-02 09:46 UTC
Labels: bug, important, macos
