### ISSUE TITLE
MAJOR: Glowing Journal is not selectable in menu

### ISSUE THREAD

**Issue by markdegica** [GooborgStudios/synglechance#43] opened 2018-05-01 16:13 UTC
The Glowing Journal is no longer selectable in Solstice. This prevents the player from progressing with the Solstice route in the mines. I've tried leaving the mines and coming back. When leaving the mines, the journal goes back to its normal state and is selectable as an item. When going back into the Mines, it goes back to its glowing state and is not selectable.

Note: The item now appears green in the menu which is the same as the items that are automatically used like the gas mask.

<img width="1280" alt="screen shot 2018-04-30 at 3 11 03 pm" src="https://user-images.githubusercontent.com/38886447/39481330-0b2d8856-4d39-11e8-83cd-3a51381f612b.png">

**Comment by markdegica** [comment] 2018-05-01 16:16
I've attached the save file with the issue present

[save.dat.zip](https://github.com/GooborgStudios/synglechance/files/1964370/save.dat.zip)

**Comment by vinyldarkscratch** [comment] 2018-05-02 09:05
Confirmed that this is an issue.  Looking into it now!

**Comment by vinyldarkscratch** [comment] 2018-05-02 09:30
I fixed this.  It looks like the Game.zip in the Dropbox folder is an outdated version, which was missing some of the Solstice content.  I just applied my patches to the newer files instead, and will have a version released ASAP.  :wink:

**Closed by vinyldarkscratch** 2018-05-02 09:30 UTC
Labels: bug, important, macos
