### ISSUE TITLE
No files in Documents/Oneshot (and other related issues)

### ISSUE THREAD

**Issue by pokedart9001** [GooborgStudios/synglechance#29] opened 2018-03-19 17:16 UTC
When I got to the part where Niko arrives inside the Tower, finds the bed and computer, and falls asleep in the bed, and then I'm told not to return, an error popped up saying it was unable to open Documents/Oneshot/_______.app/Contents/MacOS/________. Apparently either _________.app was supposed to appear in Documents/Oneshot, but it didn't. I put a symbolic link to ________.app in that folder, and after going through the "it's over" scene again, the game just closed, and when I opened it, it worked as normal. After that happened, though, I couldn't open _________.app anymore and I realized that the __________ executable inside it was completely erased and I had to download another copy of the application in order to continue the game. Also, I'm assuming save_unix.png was supposed to become my wallpaper at some point during all that, but it never did. I was able to continue the game, but unfortunately, I didn't think to take any screenshots of anything that happened. I'm running macOS High Sierra, by the way.

**Comment by vinyldarkscratch** [comment] 2018-03-19 20:20
Hey there, sorry to hear that you're having these issues!  Just to check, which macOS SyngleChance release are you using?

As for `save_unix.png`, it never set `save_w32.bmp` as the wallpaper when I played through on Windows, so I assume that's an upstream bug and/or they didn't implement it.

**Comment by KockaAdmiralac** [comment] 2018-03-19 22:16
(It did set `save_w32.bmp` as the wallpaper for me on Windows...)

**Comment by pokedart9001** [comment] 2018-03-21 03:08
@vinyldarkscratch I'm using the latest release, version 0.8.0.
@KockaAdmiralac It set `desktop.png` as my background during the Glen puzzle, so I don't know why it wouldn't here.

I also don't know why the game tried to open ________ after the Tower cutscene. From what I understand, the cutscene is supposed to play, then `save.unix.png` would be set as the wallpaper and the game would close, after which I would find __________.app in `~/Documents/Oneshot/`, open it, relaunch the game, and continue the game as normal. The weirdest part of it all was _________ being erased. I should've specified that the _contents_ of ___________ were erased, as in the file was still there but it was 0 bytes large. I saw someone else talking on the Steam discussion forums about how they accidentally closed __________.exe during the maze and when they went back to their Documents folder, the file wasn't there anymore, so maybe there was supposed to be an alias instead of a symbolic link in the folder, which would then be erased at some point? Maybe you can fill me in on what's supposed to happen, @vinyldarkscratch. I'd really appreciate that.

**Comment by vinyldarkscratch** [comment] 2018-03-21 07:24
Hmm...

This has honestly got me somewhat stumped.  Perhaps something went wrong during the install script, and it didn't copy the folder over.  Can you do me a favor and navigate to `~/Library/Application Support/Steam/steamapps/common/OneShot/`, then take a screenshot of the contents?  It would be a big help for me!

**Comment by KockaAdmiralac** [comment] 2018-03-21 12:12
I think the issue is that it's [replacing `w32` with `unix` in the `imgname` variable](https://github.com/GooborgStudios/synglechance/blob/master/binding-mri/wallpaper-binding.cpp#L108-L110) which is right after replaced with `./Wallpaper/save_w32.png`. I believe I [fixed](https://github.com/GooborgStudios/synglechance/compare/master...linux#diff-23bfd2e62122688227920778659638d1R109) this in the `linux` branch.

**Comment by vinyldarkscratch** [comment] 2018-03-22 02:18
Those fixes look great, thank you @KockaAdmiralac!

**Comment by pokedart9001** [comment] 2018-03-23 03:27
Unfortunately, I had to reinstall the game for different reasons. I don't remember why but that's not really important anyway. Point is, I can't get screenshots for the install that I had during that playthrough. Instead, here's the main and Wallpaper folders from a fresh install.
![main folder](https://user-images.githubusercontent.com/12713120/37809952-075dad3a-2e28-11e8-9e4d-1d60288775dd.png)
![wallpaper](https://user-images.githubusercontent.com/12713120/37809953-07694050-2e28-11e8-8b6c-449a0432c284.png)
What I think I'll do next is play the game up to that point again to see if the issue still occurs, and I'll post an update here when I get there.

**Comment by vinyldarkscratch** [comment] 2018-03-23 03:36
Those screenshots look right to me, yeah.  Sounds gooed to me, though, @pokedart9001!  I'm going to close the issue for now, but if it's still occurring, let me know here and I'll reopen it.  :wink:

**Comment by pokedart9001** [comment] 2018-03-23 04:35
![error](https://user-images.githubusercontent.com/12713120/37811658-f55dc476-2e31-11e8-9f2a-8f0baee9f800.png)
Yeah... the issue is still happening. But I have a screenshot this time! I can even post a video of exactly what happens if you want.

**Comment by vinyldarkscratch** [comment] 2018-03-23 04:37
Hmm...  Yes please, would you be willing to do so?

**Comment by popkirby** [comment] 2018-03-23 05:57
https://github.com/GooborgStudios/synglechance/blob/8d0c7dbb6a5eb0e33fbb9931b228030d0cd88622/src/oneshot.cpp#L446-L447

https://github.com/GooborgStudios/synglechance/blob/8d0c7dbb6a5eb0e33fbb9931b228030d0cd88622/scripts/Script.rb#L388

`OneShot::Journal` should be `_______.app` (Ruby attempts to create link in `Oneshot::GAME_PATH/Documents/_______.app/Contents/MacOS`, but no such directory exists.)

**Comment by vinyldarkscratch** [comment] 2018-03-23 06:00
Ah, I see it -- `OneShot::Journal` should technically remain as it is, because it's meant to launch the app as well.  But, it should be modified.  X3

**Comment by pokedart9001** [comment] 2018-03-23 12:07
Ok, so the link is supposed to be created in `~/Documents/Oneshot/`, not `Oneshot::GAME_PATH/Documents/`. What about the erasure of the contents of `_______.app/Contents/MacOS/_______`? Can that be explained?

**Comment by popkirby** [comment] 2018-03-23 14:14
@pokedart9001 
https://github.com/GooborgStudios/synglechance/blob/8d0c7dbb6a5eb0e33fbb9931b228030d0cd88622/scripts/Script.rb#L379-L382

`Oneshot::JOURNAL` is `"_______.app/Contents/MacOS/_______"` and is a file, so OneShot run this `if` statement. At line 381, OneShot attempts to open `~/Documents/Oneshot/_______.app/Contents/MacOS/_______`, but the directory `~/Documents/Oneshot/_______.app` does not exists, so OneShot reports error and crashes.

After creating symlink, the directory `~/Documents/Oneshot/_______.app/Contents/MacOS/` exists, so OneShot runs line 381.  When ruby opens a file with `w` flag, it makes the specified file empty.  

 `~/Documents/Oneshot/_______.app/Contents/MacOS/_______` becomes a 0 byte file, and `~/Documents/Oneshot/_______.app` is symlink to original `_______.app` under Steam directory. This means original `_______.app/Contents/MacOS/_______` becomes 0 byte too.

**Comment by pokedart9001** [comment] 2018-03-23 14:45
@popkirby I see. Thank you for the description! The solution to the first problem (trying to open `~/Documents/Oneshot/_______.app/Contents/MacOS/_______` when it doesn't exist) would seem to be creating the symlink _before_ trying to open the file, instead of after. Either that or opening the application in the game's install folder instead of in `~/Documents/Oneshot/`.

But about the second problem (causing _______ to become a 0-byte file), how might this be fixed? If _______ is erased, there's no way to reopen the journal in order to continue the game.

**Comment by pokedart9001** [comment] 2018-03-26 11:55
I think I just found out how to fix the 0-byte problem. Instead of opening `~/Documents/Oneshot/_______.app/Contents/MacOS/_______` with `w` flag, open it with `a` flag. That makes it writable without truncating the file to 0 bytes - instead, written data is appended to the end of the file.

**Comment by vinyldarkscratch** [comment] 2018-03-29 11:12
Hey @pokedart9001, I'm tackling this issue once again.  I did some brainstorming (and was also developing www.gooborg.com to get my mind off of things), and can now sit down and fix it.  😉

**Comment by pokedart9001** [comment] 2018-04-06 05:09
I just looked through the game's files a bit and I noticed something - apparently, there's an image file called `save.png` within `_______.app`'s contents:
![save](https://user-images.githubusercontent.com/12713120/38404287-df2e8d7e-3936-11e8-8bd4-243dea13e402.png)
I didn't know this file even existed until now. I assume this is supposed to appear in some form after the game's credits are finished, but I've never seen it in-game. Is this the same problem as with save_unix.png and save_w32.png? And if so, has that been fixed in the Linux branch as well?

**Comment by KockaAdmiralac** [comment] 2018-04-06 06:02
Have you opened the Journal while OneShot is running after a non-Solstice ending? If it doesn't appear there, it has most likely been fixed in the Linux branch because it works for me.

**Comment by pokedart9001** [comment] 2018-04-07 04:06
![screen shot 2018-04-07 at 12 04 22 am](https://user-images.githubusercontent.com/12713120/38451093-557344dc-39f7-11e8-89be-0e4f05149c34.png)
Just tried doing that on both non-Solstice endings and neither of them worked. You're probably right, this must've been fixed on the Linux build. I take it the notes are supposed to appear instead of the black screen and white clover when you do this?

**Comment by vinyldarkscratch** [comment] 2018-04-17 07:55
I shouldn't have said anything about being able to sit down because I totally jinxed it.  XD  I'm actually fixing it for real this time.  ;)

For the journal at the end, I assume that it might have been fixed by a recent commit.  I actually never saw that ending save.png until I was messing around with the project files (mostly because I quit out of the journal app before I would even get to there).  Based upon @KockaAdmiralac's comment though, I'm assuming it's fixed -- testing needed!

**Comment by vinyldarkscratch** [comment] 2018-04-17 08:43
This should be all fixed up in the new 0.8.1 release coming out very soon.  ;)  If it's still not working properly though, please let me know!

**Closed by vinyldarkscratch** 2018-04-17 08:43 UTC
Labels: bug, crash, important, macos
