### ISSUE TITLE
Error when building through Conan

### ISSUE THREAD

**Issue by Liz-chan** [GooborgStudios/synglechance#59] opened 2019-03-15 19:28 UTC
I'm trying to build with Conan and it keeps giving me this error. I'm guessing the package isn't there anymore?

![image](https://user-images.githubusercontent.com/18467466/54457181-1c97e200-4737-11e9-8a21-5ba3d6cf61c8.png)

**Comment by vinyldarkscratch** [comment] 2019-03-15 19:53
Hey Liz,

First off, thanks for taking interest in OneShot for Linux!  To be honest, the Conan build files are still in progress, especially in terms of the requirement for Ruby.  I highly recommend following the Qmake build instructions for the time being (it's probably what I'm going to be using for the official port, whenever I get around to deploying that).  Would you be willing to give the Qmake build a shot and see how it goes?

**Comment by Liz-chan** [comment] 2019-03-15 19:55
I did it with the build from script from KockaAdmiralac, but the the panorama around the house is wrong, and later on in the game it's wrong for another building too. Do you think it could be because it's being run in a VM?
![image](https://user-images.githubusercontent.com/18467466/54458540-9f6e6c00-473a-11e9-896d-a011dec0dc77.png)

**Comment by vinyldarkscratch** [comment] 2019-03-15 19:58
I would say it's highly probable -- I know that VMs can act weird regarding graphics like this.  What are your graphics settings for your VM like?

**Comment by Liz-chan** [comment] 2019-03-15 19:59
These are the only settings I can change concerning graphics I think, it's the default for the Ubuntu VMs.
![image](https://user-images.githubusercontent.com/18467466/54458846-5bc83200-473b-11e9-8a67-dd7d5dd64e3d.png)

**Comment by Liz-chan** [comment] 2019-03-15 20:04
When I did it on Arch with the Arch build script, the panorama was fine, so that's kinda weird.

**Comment by vinyldarkscratch** [comment] 2019-03-15 20:12
Huh, that is weird indeed...  I'm thinking that it's probably some awkward VM implementation on Ubuntu -- I seem to have no issues running it natively on Linux Mint 18.3 -- but I'll be happy to look into it more.

This is also motivating me to get back into finally publishing the Linux build, I'll admit.  After the macOS build, I moved over to working hard on getting my business developed, especially for the porting work.  Thanks for the reports, they're a big help!

**Comment by Liz-chan** [comment] 2019-03-15 20:26
That's good to know, gives me more confidence that it's just a VM issue, and I'll try my build in a Ubuntu Live Environment soon to see.

I'm glad, it took me a while to figure out everything haha, it'd be nice if newcomers could play OneShot on Linux without having to do all the compiling. I'm happy to help 😄

I noticed that by moving the game from the Ubuntu you compiled it from, to a stock one, it's missing some shared libraries and doesn't start. Is there any way to include those so that you can transfer it to a new one without compiling again?

**Comment by KockaAdmiralac** [comment] 2019-03-15 20:28
What shared libraries is it missing? You can use `ldd OneShot | grep "not found"` on the OneShot executable to see what is it trying to search for.

**Comment by Liz-chan** [comment] 2019-03-15 20:31
![image](https://user-images.githubusercontent.com/18467466/54460366-b8c5e700-473f-11e9-9784-e51b73e4ab45.png)

Here you go.

**Comment by KockaAdmiralac** [comment] 2019-03-15 20:37
- `libboost_program_options` is from the `libboost-all-dev` package.
- `libopenal` is from the `libalut-dev` package.
- `libxfconf` is from the `libxfconf-0-dev` package.
- `libruby` is from `ruby2.3` and `ruby2.3-dev` packages.
- `libphysfs` and `libSDL*` packages have to be manually compiled because their versions that OneShot requires are not available on Aptitude. Lines from the build script that you can run for that are [these](https://gist.github.com/KockaAdmiralac/9155baba75f9e684cc5a0e7826d81526#file-1-debian-sh-L11-L61).

**Comment by vinyldarkscratch** [comment] 2019-03-15 21:02
A little correction: the libSDL_sound is [Ancurio's fork](https://github.com/Ancurio/SDL_sound).  We'll definitely be packaging these libraries in with the official release!

**Comment by KockaAdmiralac** [comment] 2019-03-15 22:25
I just looked around the game files and it looks like the starting map indeed has that image as a panorama, but the map's background is covered in black tiles. These tiles appear to be transparent instead of black for you, though. Can you check if your game files, specifically `Graphics/Autotiles/black.png` and `Data/Map002.rxdata` are the same files as in the Windows/macOS versions of OneShot? Does `black.png` appear as black in your image viewer?

**Comment by Liz-chan** [comment] 2019-03-15 22:34
I checked in a Live CD for Ubuntu and it was still the same, so it wasn't because of the VM, it was because I compiled on Ubuntu I guess, since that didn't happen in arch.

Also I just checked and yes, they're the same files, and it does look black on my image viewer, it's strange.

**Comment by vinyldarkscratch** [comment] 2019-03-15 23:13
Hmm, that's odd, considering that Linux Mint is a sub-OS of Ubuntu...  It may be some odd layer rendering thing going on.  I'll have to look into that more!

**Comment by Liz-chan** [comment] 2019-03-16 01:14
Sadly it happened to me too on Mint, don't know what I'm doing wrong.

![image](https://user-images.githubusercontent.com/18467466/54468846-41a44900-4767-11e9-8992-f31a62092783.png)

**Comment by KockaAdmiralac** [comment] 2019-04-07 00:54
Hey, sorry for taking longer to respond, I've encountered some hard drive issues around the time I was trying to reproduce this. I think I managed to reproduce the issue with images randomly being shown as transparent, but not on the exact same image. I've split this issue into two issues for easier tracking, so I'll close this one. Thank you for bringing it to our attention!

**Closed by KockaAdmiralac** 2019-04-07 00:54 UTC
Labels: conan, linux
